services:
  backend:
    container_name: backend
    image: coooolkpk/aces-website-backend:v1.4
    expose:
      - 5000
    #ports:
    #  - "5000:5000"    
    environment:
      - PORT=5000
      - MONGODB_URI=######
      - EMAIL_USER=
      - EMAIL_PASS=
    networks:
      - aces-network
  frontend:
    container_name: frontend
    image: coooolkpk/aces-website-frontend:v1.5
    ports:
      - "9081:80"
#    environment:
#      - REACT_APP_BACKEND_URL=https://innoverse.acespvgcoet.in
    depends_on:
      - backend
    networks:
      - aces-network
networks:
  aces-network:
    driver: bridge

#      - backend
#      - frontend
